"""Portas — o que a aplicação exige do mundo, sem saber quem entrega.

É o que permite testar caso de uso sem banco. Ver docs/CONTRATOS.md.
"""

from __future__ import annotations

from typing import Protocol

from cat.dominio.acesso.usuario import Cargo, Papel, Usuario


class RepositorioUsuario(Protocol):
    # leitura
    def buscar_por_usuario(self, usuario: str) -> Usuario | None: ...
    def buscar_por_email(self, email: str) -> Usuario | None: ...
    def buscar_por_id(self, usuario_id: int) -> Usuario | None: ...
    def listar(self) -> list[Usuario]: ...
    def contar_gestores_ativos(self) -> int: ...
    def obter_hash_senha(self, usuario_id: int) -> str: ...

    # escrita
    def criar(
        self, *, usuario: str, email: str, nome_exibicao: str, senha_hash: str,
        papel: Papel, cargo: Cargo, senha_provisoria: bool,
    ) -> Usuario: ...
    def salvar_tentativa(self, usuario: Usuario) -> None: ...
    def regravar_hash_senha(self, usuario_id: int, novo_hash: str) -> None: ...
    def definir_senha(
        self, usuario_id: int, novo_hash: str, *, provisoria: bool
    ) -> None: ...
    def definir_papel(self, usuario_id: int, papel: Papel) -> None: ...
    def definir_cargo(self, usuario_id: int, cargo: Cargo) -> None: ...
    def definir_situacao(self, usuario_id: int, ativo: bool) -> None: ...
    def desbloquear(self, usuario_id: int) -> None: ...


class VerificadorDeSenha(Protocol):
    def conferir(self, senha: str, hash_armazenado: str) -> bool: ...
    def precisa_regravar(self, hash_armazenado: str) -> bool: ...
    def gerar(self, senha: str) -> str: ...


class EmissorDeToken(Protocol):
    def emitir(self, usuario: Usuario) -> tuple[str, int]:
        """Devolve o token e por quantos segundos ele vale."""
        ...
