"""Descrições de CFOP (Código Fiscal de Operações e Prestações).

Cobre a tabela oficial completa de CFOP — ENTRADA (1xxx/2xxx/3xxx) e
SAÍDA (5xxx/6xxx/7xxx), ~540 códigos folha (exclui cabeçalhos de grupo
tipo 1.100/5.900). Usada tanto para a coluna DESCRICAO_CFOP dos joins
exportados quanto para o filtro de CFOP na UI (mostra "código - descrição").

Códigos marcados com # CONFIRMADO foram extraídos diretamente de arquivos
de referência reais:
  - "037 - Entradas" (empresa A, jul-dez/2021) — grupo 1/2/3xxx
  - "C100, C170, 0200 - Documento e Itens - Nota Fiscal" (empresa C,
    out/2024) — grupo 5/6xxx e alguns 1xxx adicionais
Os códigos na seção "Demais códigos oficiais" (uma por grupo) vêm da tabela
oficial de CFOP (Ajuste SINIEF 07/01), abreviados automaticamente no mesmo
estilo dos confirmados, e ainda não foram confrontados com um arquivo de
referência real — em caso de divergência com um relatório real, o texto
CONFIRMADO acima sempre prevalece.

Adicionar novos códigos aqui não exige nenhuma mudança de código.
"""

# Copiada do projeto Quebra de SPED em 22/09/2026, sem alteração de conteúdo.
# As marcas "# CONFIRMADO" indicam o que foi conferido contra arquivo de
# referência real — não as remova ao acrescentar entradas novas: elas são a
# diferença entre o que se sabe e o que se supõe.

from __future__ import annotations

TABELA: dict[str, str] = {
    # ── Entrada (1xxx/2xxx/3xxx) ────────────────────────────────────────────
    "1101": "Compra p/indust ou prod rural",  # CONFIRMADO (MA)
    "1102": "Compra p/comercial",  # CONFIRMADO (MA)
    "1113": "Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil",
    "1122": "Compra p/indust quando mercad remetida pelo fornec ao industizador sem transitar pelo estab adquir",  # CONFIRMADO (MA)
    "1201": "Devolução de venda de produção do estabelecimento",
    "1202": "Devol Venda mercad adq/receb terc",  # CONFIRMADO (MA)
    "1401": "Compra p/indust ou prod rural de mercad sujeita a ST",  # CONFIRMADO (MA)
    "1403": "Compra p/comercial em operação com mercad sujeita a ST",  # CONFIRMADO (MA)
    "1406": "Compra bem p/o ativo imob cuja mercad está sujeita a ST",  # CONFIRMADO (MA)
    "1407": "Compra mercad p/uso ou consumo cuja mercad está sujeita a ST",  # CONFIRMADO (MA)
    "1411": "Devol Venda mercad adq/receb terc em operação com mercad sujeita a ST",  # CONFIRMADO (MA)
    "1551": "Compra bem p/o ativo imob",  # CONFIRMADO (MA)
    "1556": "Compra material p/uso ou consumo",  # CONFIRMADO (MA)
    "1652": "Compra comb/lubrif p/comercial",  # CONFIRMADO (MA)
    "1653": "Compra comb/lubrif por consum ou usuário final",  # CONFIRMADO (MA)
    "1908": "Entr de bem conta de contrato de comodato",  # CONFIRMADO (MA)
    "1910": "Entr de bonificação, doação ou brinde",  # CONFIRMADO (MA)
    "1916": "Ret mercad ou bem remetido p/conserto ou reparo",  # CONFIRMADO (MA)
    "1933": "Aquisição de serviço tributado pelo ISSQN",
    "1949": "Outra Entr de mercad ou prestação de serv não especificada",  # CONFIRMADO (MA)
    "2101": "Compra p/indust ou prod rural",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "2102": "Compra p/comercial",  # CONFIRMADO (MA)
    "2113": "Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil",
    "2202": "Devol Venda mercad adq/receb terc",
    "2401": "Compra p/indust ou prod rural de mercad sujeita a ST",
    "2403": "Compra p/comercial em operação com mercad sujeita a ST",  # CONFIRMADO (MA)
    "2407": "Compra mercad p/uso ou consumo cuja mercad está sujeita a ST",  # CONFIRMADO (MA)
    "2411": "Devol Venda mercad adq/receb terc em operação com mercad sujeita a ST",
    "2551": "Compra bem p/o ativo imob",  # CONFIRMADO (MA)
    "2556": "Compra material p/uso ou consumo",  # CONFIRMADO (MA)
    "2653": "Compra de combustível ou lubrificante para comercialização",
    "2933": "Aquisição de serviço tributado pelo ISSQN",
    "2949": "Outra Entr de mercad ou prestação de serv não especificado",  # CONFIRMADO (MA)
    "3102": "Compra p/comercial",
    "3126": "Compra para utilização na prestação de serviço sujeita ao ICMS",
    "3556": "Compra de material para uso ou consumo",

    # Demais códigos oficiais (tabela CFOP completa, não confirmados
    # contra dado real deste projeto) — descrições abreviadas a partir do
    # texto oficial do Guia Prático EFD-Contribuições / Convênio s/n de 1970.
    "1111": 'Compra p/indust de mercad receb anteriorm em consig indust',
    "1116": 'Compra p/indust ou prod rural originada de encomenda p/ recebimento futuro',
    "1117": 'Compra p/comercial originada de encomenda p/ recebimento futuro',
    "1118": 'Compra de mercad p/comercial pelo adquir originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem',
    "1120": 'Compra p/indust, em venda à ordem, já recebida do vendedor remetente',
    "1121": "Compra p/comercial, em venda à ordem, já recebida do vendedor remet",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "1124": 'Indust efetuada por outra empresa',
    "1125": 'Indust efetuada por outra empresa quando a mercad remet p/ utilização no processo de indust sem trânsito pelo estab a...',
    "1126": 'Compras p/ utilização na prest servs sujeitas ao ICMS',
    "1128": 'Compras p/ utilização na prest servs sujeitas ao ISSQN',
    "1151": 'Transferência p/indust ou prod rural',
    "1152": 'Transferência p/comercial',
    "1153": 'Transferência de energ elétr p/ distribuição',
    "1154": 'Transferência p/ utilização na prest serv',
    "1203": 'Devolução de venda de produção do estab, destinada à ZFM/ALC',
    "1204": 'Devolução de venda de mercad adq/receb terc, destinada à ZFM/ALC',
    "1205": 'Anulação de valor relativo à prest serv de comunicação',
    "1206": 'Anulação de valor relativo à prest serv de transporte',
    "1207": 'Anulação de valor relativo à venda de energ elétr',
    "1208": 'Devolução de produção do estab, remetida em transferência',
    "1209": 'Devolução de mercad adq/receb terc, remetida em transferência',
    "1251": 'Compra de energ elétr p/ distribuição ou comercial',
    "1252": 'Compra de energ elétr por estab industrial',
    "1253": 'Compra de energ elétr por estab comercial',
    "1254": 'Compra de energ elétr por estab prest serv transporte',
    "1255": 'Compra de energ elétr por estab prest serv comunicação',
    "1256": 'Compra de energ elétr por estab de produtor rural',
    "1257": 'Compra de energ elétr p/ consumo por demanda contratada',
    "1301": 'Aquisição de serviço de comunicação p/ execução de serv mesma natureza',
    "1302": 'Aquisição de serviço de comunicação por estab industrial',
    "1303": 'Aquisição de serviço de comunicação por estab comercial',
    "1304": 'Aquisição de serviço de comunicação por estab de prest serv transporte',
    "1305": 'Aquisição de serviço de comunicação por estab de geradora/distrib de energ elétr',
    "1306": 'Aquisição de serviço de comunicação por estab de produtor rural',
    "1351": 'Aquisição de serviço de transporte p/ execução de serv mesma natureza',
    "1352": 'Aquisição de serviço de transporte por estab industrial',
    "1353": 'Aquisição de serviço de transporte por estab comercial',
    "1354": 'Aquisição de serviço de transporte por estab de prest serv comunicação',
    "1355": 'Aquisição de serviço de transporte por estab de geradora/distrib de energ elétr',
    "1356": 'Aquisição de serviço de transporte por estab de produtor rural',
    "1360": 'Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte',
    "1408": 'Transferência p/indust ou prod rural em operação c/ mercad sujeita a ST',
    "1409": 'Transferência p/comercial em operação c/ mercad sujeita a ST',
    "1410": 'Devolução de venda de produção do estab em operação c/ produto sujeito a ST',
    "1414": 'Retorno de produção do estab, remetida p/venda fora do estab em operação c/ produto sujeito a ST',
    "1415": 'Retorno de mercad adq/receb terc, remetida p/venda fora do estab em operação c/ mercad sujeita a ST',
    "1451": 'Retorno de animal do estab produtor',
    "1452": 'Retorno de insumo não utilizado na produção',
    "1501": 'Entrada de mercad recebida c/fim espec exportação',
    "1503": 'Entrada decorrente de devolução de produto remetido c/fim espec exportação, de produção do estab',
    "1504": 'Entrada decorrente de devolução de mercad remetida c/fim espec exportação, adq/receb terc',
    "1505": 'Entrada decorrente de devolução simbólica de mercads remetidas p/ formação de lote de exportação, de produtos industr...',
    "1506": 'Entrada decorrente de devolução simbólica de mercads, adq/receb terc, remetidas p/ formação de lote de exportação',
    "1552": 'Transferência de bem do ativo imob',
    "1553": 'Devolução de venda de bem do ativo imob',
    "1554": 'Retorno de bem do ativo imob remet p/ uso fora do estab',
    "1555": 'Entrada de bem do ativo imob de terceiro, remet p/ uso no estab',
    "1557": 'Transferência de material p/uso/consumo',
    "1601": 'Recebimento, por transferência, de crédito de ICMS',
    "1602": 'Recebimento, por transferência, de saldo credor de ICMS de outro estab da mesma empresa, p/ compensação de saldo deve...',
    "1603": 'Ressarcimento de ICMS retido por ST',
    "1604": 'Lançamento do crédito relativo à compra de bem p/ o ativo imob',
    "1605": 'Recebimento, por transferência, de saldo devedor de ICMS de outro estab da mesma empresa',
    "1658": 'Transferência de comb/lubrif p/indust',
    "1659": 'Transferência de comb/lubrif p/comercial',
    "1660": 'Devolução de venda de comb/lubrif destinado à indust subsequente',
    "1661": 'Devolução de venda de comb/lubrif destinado à comercial',
    "1662": 'Devolução de venda de comb/lubrif destinado a consum/usuár final',
    "1663": 'Entrada de comb/lubrif p/ armazenagem',
    "1664": 'Retorno de comb/lubrif remet p/ armazenagem',
    "1901": 'Entrada p/indust por encomenda',
    "1902": 'Retorno de mercad remetida p/indust por encomenda',
    "1903": 'Entrada de mercad remetida p/indust e não aplicada no referido processo',
    "1904": 'Retorno de remessa p/venda fora do estab',
    "1905": 'Entrada de mercad receb p/ depósito em depós fechado/armaz geral',
    "1906": 'Retorno de mercad remet p/ depós fechado/armaz geral',
    "1907": 'Retorno simbólico de mercad remet p/ depós fechado/armaz geral',
    "1909": 'Retorno de bem remetido por conta de contrato de comodato',
    "1911": 'Entrada de amostra grátis',
    "1912": 'Entrada de mercad ou bem receb p/ demonstração',
    "1913": 'Retorno de mercad ou bem remet p/ demonstração',
    "1914": 'Retorno de mercad ou bem remet p/ exposição/feira',
    "1915": 'Entrada de mercad ou bem receb p/ conserto/reparo',
    "1917": 'Entrada de mercad recebida em consig mercantil/indust',
    "1918": 'Devolução de mercad remetida em consig mercantil/indust',
    "1919": 'Devolução simbólica de mercad vendida ou utilizada em processo industrial, remet anteriorm em consig mercantil/indust',
    "1920": 'Entrada de vasilhame/sacaria',
    "1921": 'Retorno de vasilhame/sacaria',
    "1922": 'Lanç a título de simples faturamento decorrente de compra p/ recebimento futuro',
    "1923": 'Entrada de mercad recebida do vendedor remetente, em venda à ordem',
    "1924": 'Entrada p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do adquirente',
    "1925": 'Retorno de mercad remetida p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do a...',
    "1926": 'Lanç a título de reclassificação de mercad decorrente de formação de kit ou de sua desagregação',
    "1931": 'Lanç efetuado pelo tomador do serviço de transporte quando a responsab retenção imposto for atribuída ao remetente ou...',
    "1932": 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde inscrito o prestador',
    "2111": 'Compra p/indust de mercad receb anteriorm em consig indust',
    "2116": 'Compra p/indust ou prod rural originada de encomenda p/ recebimento futuro',
    "2117": 'Compra p/comercial originada de encomenda p/ recebimento futuro',
    "2118": 'Compra de mercad p/comercial pelo adquir originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem',
    "2120": 'Compra p/indust, em venda à ordem, já recebida do vendedor remetente',
    "2121": "Compra p/comercial, em venda à ordem, já recebida do vendedor remet",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "2122": 'Compra p/indust em que a mercad foi remetida pelo fornecedor ao industrializador sem transitar pelo estab adquirente',
    "2124": 'Indust efetuada por outra empresa',
    "2125": 'Indust efetuada por outra empresa quando a mercad remet p/ utilização no processo de indust sem trânsito pelo estab a...',
    "2126": 'Compra p/ utilização na prest serv',
    "2151": 'Transferência p/indust ou prod rural',
    "2152": 'Transferência p/comercial',
    "2153": 'Transferência de energ elétr p/ distribuição',
    "2154": 'Transferência p/ utilização na prest serv',
    "2201": 'Devolução de venda de produção do estab',
    "2203": 'Devolução de venda de produção do estab, destinada à ZFM/ALC',
    "2204": 'Devolução de venda de mercad adq/receb terc, destinada à ZFM/ALC',
    "2205": 'Anulação de valor relativo à prest serv de comunicação',
    "2206": 'Anulação de valor relativo à prest serv de transporte',
    "2207": 'Anulação de valor relativo à venda de energ elétr',
    "2208": 'Devolução de produção do estab, remetida em transferência',
    "2209": 'Devolução de mercad adq/receb terc, remetida em transferência',
    "2251": 'Compra de energ elétr p/ distribuição ou comercial',
    "2252": 'Compra de energ elétr por estab industrial',
    "2253": 'Compra de energ elétr por estab comercial',
    "2254": 'Compra de energ elétr por estab prest serv transporte',
    "2255": 'Compra de energ elétr por estab prest serv comunicação',
    "2256": 'Compra de energ elétr por estab de produtor rural',
    "2257": 'Compra de energ elétr p/ consumo por demanda contratada',
    "2301": 'Aquisição de serviço de comunicação p/ execução de serv mesma natureza',
    "2302": 'Aquisição de serviço de comunicação por estab industrial',
    "2303": 'Aquisição de serviço de comunicação por estab comercial',
    "2304": 'Aquisição de serviço de comunicação por estab de prest serv transporte',
    "2305": 'Aquisição de serviço de comunicação por estab de geradora/distrib de energ elétr',
    "2306": 'Aquisição de serviço de comunicação por estab de produtor rural',
    "2351": 'Aquisição de serviço de transporte p/ execução de serv mesma natureza',
    "2352": 'Aquisição de serviço de transporte por estab industrial',
    "2353": 'Aquisição de serviço de transporte por estab comercial',
    "2354": 'Aquisição de serviço de transporte por estab de prest serv comunicação',
    "2355": 'Aquisição de serviço de transporte por estab de geradora/distrib de energ elétr',
    "2356": 'Aquisição de serviço de transporte por estab de produtor rural',
    "2406": 'Compra de bem p/ o ativo imob cuja mercad está sujeita a ST',
    "2408": 'Transferência p/indust ou prod rural em operação c/ mercad sujeita a ST',
    "2409": 'Transferência p/comercial em operação c/ mercad sujeita a ST',
    "2410": 'Devolução de venda de produção do estab em operação c/ produto sujeito a ST',
    "2414": 'Retorno de produção do estab, remetida p/venda fora do estab em operação c/ produto sujeito a ST',
    "2415": 'Retorno de mercad adq/receb terc, remetida p/venda fora do estab em operação c/ mercad sujeita a ST',
    "2501": 'Entrada de mercad recebida c/fim espec exportação',
    "2503": 'Entrada decorrente de devolução de produto remetido c/fim espec exportação, de produção do estab',
    "2504": 'Entrada decorrente de devolução de mercad remetida c/fim espec exportação, adq/receb terc',
    "2505": 'Entrada decorrente de devolução simbólica de mercads remetidas p/ formação de lote de exportação, de produtos industr...',
    "2506": 'Entrada decorrente de devolução simbólica de mercads, adq/receb terc, remetidas p/ formação de lote de exportação',
    "2552": 'Transferência de bem do ativo imob',
    "2553": 'Devolução de venda de bem do ativo imob',
    "2554": 'Retorno de bem do ativo imob remet p/ uso fora do estab',
    "2555": 'Entrada de bem do ativo imob de terceiro, remet p/ uso no estab',
    "2557": 'Transferência de material p/uso/consumo',
    "2603": 'Ressarcimento de ICMS retido por ST',
    "2651": 'Compra de comb/lubrif p/indust subsequente',
    "2652": 'Compra de comb/lubrif p/comercial',
    "2658": 'Transferência de comb/lubrif p/indust',
    "2659": 'Transferência de comb/lubrif p/comercial',
    "2660": 'Devolução de venda de comb/lubrif destinado à indust subsequente',
    "2661": 'Devolução de venda de comb/lubrif destinado à comercial',
    "2662": 'Devolução de venda de comb/lubrif destinado a consum/usuár final',
    "2663": 'Entrada de comb/lubrif p/ armazenagem',
    "2664": 'Retorno de comb/lubrif remet p/ armazenagem',
    "2901": 'Entrada p/indust por encomenda',
    "2902": 'Retorno de mercad remetida p/indust por encomenda',
    "2903": 'Entrada de mercad remetida p/indust e não aplicada no referido processo',
    "2904": 'Retorno de remessa p/venda fora do estab',
    "2905": 'Entrada de mercad receb p/ depósito em depós fechado/armaz geral',
    "2906": 'Retorno de mercad remet p/ depós fechado/armaz geral',
    "2907": 'Retorno simbólico de mercad remet p/ depós fechado/armaz geral',
    "2908": 'Entrada de bem por conta de contrato de comodato',
    "2909": 'Retorno de bem remetido por conta de contrato de comodato',
    "2910": 'Entrada de bonif/doação/brinde',
    "2911": 'Entrada de amostra grátis',
    "2912": 'Entrada de mercad ou bem receb p/ demonstração',
    "2913": 'Retorno de mercad ou bem remet p/ demonstração',
    "2914": 'Retorno de mercad ou bem remet p/ exposição/feira',
    "2915": 'Entrada de mercad ou bem receb p/ conserto/reparo',
    "2916": 'Retorno de mercad ou bem remet p/ conserto/reparo',
    "2917": 'Entrada de mercad recebida em consig mercantil/indust',
    "2918": 'Devolução de mercad remetida em consig mercantil/indust',
    "2919": 'Devolução simbólica de mercad vendida ou utilizada em processo industrial, remet anteriorm em consig mercantil/indust',
    "2920": 'Entrada de vasilhame/sacaria',
    "2921": 'Retorno de vasilhame/sacaria',
    "2922": 'Lanç a título de simples faturamento decorrente de compra p/ recebimento futuro',
    "2923": 'Entrada de mercad recebida do vendedor remetente, em venda à ordem',
    "2924": 'Entrada p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do adquirente',
    "2925": 'Retorno de mercad remetida p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do a...',
    "2931": 'Lanç efetuado pelo tomador do serviço de transporte quando a responsab retenção imposto for atribuída ao remetente ou...',
    "2932": 'Aquisição de serviço de transporte iniciado em UF diversa daquela onde inscrito o prestador',
    "3101": 'Compra p/indust ou prod rural',
    "3127": 'Compra p/indust sob o regime de drawback',
    "3201": 'Devolução de venda de produção do estab',
    "3202": 'Devolução de venda de mercad adq/receb terc',
    "3205": 'Anulação de valor relativo à prest serv de comunicação',
    "3206": 'Anulação de valor relativo à prest serv de transporte',
    "3207": 'Anulação de valor relativo à venda de energ elétr',
    "3211": 'Devolução de venda de produção do estab sob o regime de drawback',
    "3251": 'Compra de energ elétr p/ distribuição ou comercial',
    "3301": 'Aquisição de serviço de comunicação p/ execução de serv mesma natureza',
    "3351": 'Aquisição de serviço de transporte p/ execução de serv mesma natureza',
    "3352": 'Aquisição de serviço de transporte por estab industrial',
    "3353": 'Aquisição de serviço de transporte por estab comercial',
    "3354": 'Aquisição de serviço de transporte por estab de prest serv comunicação',
    "3355": 'Aquisição de serviço de transporte por estab de geradora/distrib de energ elétr',
    "3356": 'Aquisição de serviço de transporte por estab de produtor rural',
    "3503": 'Devolução de mercad exportada que tenha sido recebida c/fim espec exportação',
    "3551": 'Compra de bem p/ o ativo imob',
    "3553": 'Devolução de venda de bem do ativo imob',
    "3651": 'Compra de comb/lubrif p/indust subsequente',
    "3652": 'Compra de comb/lubrif p/comercial',
    "3653": 'Compra de comb/lubrif por consum/usuár final',
    "3930": 'Lanç a título de entrada de bem sob amparo regime especial aduaneiro admissão temp',
    "3949": 'Outra entrada de mercad ou prest serv não espec',

    # ── Saída (5xxx/6xxx/7xxx) ───────────────────────────────────────────────
    "5101": "Venda prod do estab",  # texto oficial abreviado (estava trocado com 1101)
    "5102": "Venda mercad adq/receb terc",  # CONFIRMADO (MA)
    "5201": "Devol venda p/comercial",
    "5202": "Devol compra p/comercial",  # CONFIRMADO (MA)
    "5405": "Venda mercad, adq/receb terc, sujeita a ST, na condição de contrib-substituído",  # CONFIRMADO (MA)
    "5411": "Devol compra p/comercial em operação com mercad sujeita a ST",  # CONFIRMADO (MA)
    "5551": "Venda bem do ativo imob",
    "5556": "Venda material p/uso ou consumo",
    "5910": "Remes em bonificação, doação ou brinde",
    "5915": "Remes de mercad ou bem p/conserto ou reparo",  # CONFIRMADO (MA)
    "5916": "Retorno de mercad ou bem recebido p/conserto ou reparo",
    "5927": "Lanç efetuado a título de baixa de estoquecor de perda, roubo ou deterioração",  # CONFIRMADO (MA)
    "5949": "Outra saída de mercad ou prestação de serv não especificado",
    "6101": "Venda prod do estab",  # texto oficial abreviado (estava trocado com 1101)
    "6102": "Venda mercad adq/receb terc",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "6202": "Devol compra p/comercial",  # CONFIRMADO (MA)
    "6411": "Devol compra p/comercial em operação com mercad sujeita a ST",
    "6551": "Venda bem do ativo imob",
    "6556": "Venda material p/uso ou consumo",
    "6949": "Outra saída de mercad ou prestação de serv não especificado",
    "7102": "Venda p/comercial no exterior",
    "7949": "Outra saída de mercad ou prestação de serv não especificado",

    # Demais códigos oficiais (tabela CFOP completa, não confirmados
    # contra dado real deste projeto) — descrições abreviadas a partir do
    # texto oficial do Guia Prático EFD-Contribuições / Convênio s/n de 1970.
    "5103": 'Venda de produção do estab, efetuada fora do estab',
    "5104": 'Venda de mercad adq/receb terc, efetuada fora do estab',
    "5105": 'Venda de produção do estab sem trânsito pelo estab',
    "5106": 'Venda de mercad adq/receb terc, sem trânsito pelo estab',
    "5109": 'Venda de produção do estab, destinada à ZFM/ALC',
    "5110": 'Venda de mercad adq/receb terc, destinada à ZFM/ALC',
    "5111": 'Venda de produção do estab remet anteriorm em consig indust',
    "5112": 'Venda de mercad adq/receb terc remet anteriorm em consig indust',
    "5113": 'Venda de produção do estab remet anteriorm em consig mercantil',
    "5114": 'Venda de mercad adq/receb terc remet anteriorm em consig mercantil',
    "5115": 'Venda de mercad adq/receb terc, receb anteriorm em consig mercantil',
    "5116": 'Venda de produção do estab originada de encomenda p/ entrega futura',
    "5117": 'Venda de mercad adq/receb terc, originada de encomenda p/ entrega futura',
    "5118": 'Venda de produção do estab entregue ao destinatário por conta/ordem do adquir originário, em venda à ordem',
    "5119": 'Venda de mercad adq/receb terc entregue ao destinatário por conta/ordem do adquir originário, em venda à ordem',
    "5120": 'Venda de mercad adq/receb terc entregue ao destinatário pelo vendedor remetente, em venda à ordem',
    "5122": 'Venda de produção do estab remetida p/indust, por conta/ordem do adquirente, sem transitar pelo estab do adquirente',
    "5123": 'Venda de mercad adq/receb terc remetida p/indust, por conta/ordem do adquirente, sem transitar pelo estab do adquirente',
    "5124": 'Indust efetuada p/ outra empresa',
    "5125": 'Indust efetuada p/ outra empresa quando a mercad receb p/ utilização no processo de indust sem trânsito pelo estab ad...',
    "5151": 'Transferência de produção do estab',
    "5152": "Transf mercad adq/receb terc",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5153": 'Transferência de energ elétr',
    "5155": 'Transferência de produção do estab, sem trânsito pelo estab',
    "5156": 'Transferência de mercad adq/receb terc, sem trânsito pelo estab',
    "5205": 'Anulação de valor relativo a aquisição de serviço de comunicação',
    "5206": 'Anulação de valor relativo a aquisição de serviço de transporte',
    "5207": 'Anulação de valor relativo à compra de energ elétr',
    "5208": 'Devolução de mercad recebida em transferência p/indust ou prod rural',
    "5209": 'Devolução de mercad recebida em transferência p/comercial',
    "5210": 'Devolução de compra p/ utilização na prest serv sujeitas ao ICMS ou ISSQN',
    "5251": 'Venda de energ elétr p/ distribuição ou comercial',
    "5252": 'Venda de energ elétr p/ estab industrial',
    "5253": 'Venda de energ elétr p/ estab comercial',
    "5254": 'Venda de energ elétr p/ estab prest serv transporte',
    "5255": 'Venda de energ elétr p/ estab prest serv comunicação',
    "5256": 'Venda de energ elétr p/ estab de produtor rural',
    "5257": 'Venda de energ elétr p/ consumo por demanda contratada',
    "5258": 'Venda de energ elétr a não contribuinte',
    "5301": 'Prest serv de comunicação p/ execução de serv mesma natureza',
    "5302": 'Prest serv de comunicação a estab industrial',
    "5303": 'Prest serv de comunicação a estab comercial',
    "5304": 'Prest serv de comunicação a estab de prest serv transporte',
    "5305": 'Prest serv de comunicação a estab de geradora/distrib de energ elétr',
    "5306": 'Prest serv de comunicação a estab de produtor rural',
    "5307": 'Prest serv de comunicação a não contribuinte',
    "5351": 'Prest serv de transporte p/ execução de serv mesma natureza',
    "5352": 'Prest serv de transporte a estab industrial',
    "5353": 'Prest serv de transporte a estab comercial',
    "5354": 'Prest serv de transporte a estab de prest serv comunicação',
    "5355": 'Prest serv de transporte a estab de geradora/distrib de energ elétr',
    "5356": 'Prest serv de transporte a estab de produtor rural',
    "5357": 'Prest serv de transporte a não contribuinte',
    "5359": 'Prest serv de transporte a contribuinte ou a não contribuinte quando a mercad transportada está dispensada de emissão...',
    "5360": 'Prest serv de transporte a contribuinte substituto em relação ao serviço de transporte',
    "5401": "Venda prod do estab quando o prod esteja sujeito a ST",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5402": "Venda prod do estab de prod sujeito a ST, em operação entre contribs substitutos do mesmo prod",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5403": "Venda mercad, adq/receb terc, sujeita a ST, na condição de contrib-substituto",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5408": 'Transferência de produção do estab em operação c/ produto sujeito a ST',
    "5409": "Transf mercad adq/receb terc em operação com mercad sujeita a ST",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5410": 'Devolução de compra p/indust ou prod rural em operação c/ mercad sujeita a ST',
    "5412": 'Devolução de bem do ativo imob, em operação c/ mercad sujeita a ST',
    "5413": 'Devolução de mercad destinada ao uso/consumo, em operação c/ mercad sujeita a ST',
    "5414": 'Remessa de produção do estab p/venda fora do estab em operação c/ produto sujeito a ST',
    "5415": 'Remessa de mercad adq/receb terc p/venda fora do estab, em operação c/ mercad sujeita a ST',
    "5451": 'Remessa de animal e de insumo p/ estab produtor',
    "5501": 'Remessa de produção do estab, c/fim espec exportação',
    "5502": 'Remessa de mercad adq/receb terc, c/fim espec exportação',
    "5503": 'Devolução de mercad recebida c/fim espec exportação',
    "5504": 'Remessa de mercads p/ formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estab',
    "5505": 'Remessa de mercads, adq/receb terc, p/ formação de lote de exportação',
    "5552": 'Transferência de bem do ativo imob',
    "5553": 'Devolução de compra de bem p/ o ativo imob',
    "5554": 'Remessa de bem do ativo imob p/ uso fora do estab',
    "5555": 'Devolução de bem do ativo imob de terceiro, receb p/ uso no estab',
    "5557": 'Transferência de material de uso/consumo',
    "5601": 'Transferência de crédito de ICMS acumulado',
    "5602": 'Transferência de saldo credor de ICMS p/ outro estab da mesma empresa, destinado à compensação de saldo devedor de ICMS',
    "5603": 'Ressarcimento de ICMS retido por ST',
    "5605": 'Transferência de saldo devedor de ICMS de outro estab da mesma empresa',
    "5606": 'Utilização de saldo credor de ICMS p/ extinção por compensação de débitos fiscais',
    "5651": 'Venda de comb/lubrif de produção do estab destinado à indust subsequente',
    "5652": 'Venda de comb/lubrif de produção do estab destinado à comercial',
    "5653": 'Venda de comb/lubrif de produção do estab destinado a consum/usuár final',
    "5654": 'Venda de comb/lubrif adq/receb terc destinado à indust subsequente',
    "5655": 'Venda de comb/lubrif adq/receb terc destinado à comercial',
    "5656": 'Venda de comb/lubrif adq/receb terc destinado a consum/usuár final',
    "5657": 'Remessa de comb/lubrif adq/receb terc p/venda fora do estab',
    "5658": 'Transferência de comb/lubrif de produção do estab',
    "5659": 'Transferência de comb/lubrif adquirido ou recebido de terceiro',
    "5660": 'Devolução de compra de comb/lubrif adquirido p/indust subsequente',
    "5661": 'Devolução de compra de comb/lubrif adquirido p/comercial',
    "5662": 'Devolução de compra de comb/lubrif adquirido por consum/usuár final',
    "5663": 'Remessa p/ armazenagem de comb/lubrif',
    "5664": 'Retorno de comb/lubrif receb p/ armazenagem',
    "5665": 'Retorno simbólico de comb/lubrif receb p/ armazenagem',
    "5666": 'Remessa por conta e ordem de terceiros de comb/lubrif receb p/ armazenagem',
    "5901": 'Remessa p/indust por encomenda',
    "5902": 'Retorno de mercad utilizada na indust por encomenda',
    "5903": 'Retorno de mercad recebida p/indust e não aplicada no referido processo',
    "5904": 'Remessa p/venda fora do estab',
    "5905": 'Remessa p/ depós fechado/armaz geral',
    "5906": "Ret mercad depositada em dep fechado ou armazém geral",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "5907": 'Retorno simbólico de mercad depositada em depós fechado/armaz geral',
    "5908": 'Remessa de bem por conta de contrato de comodato',
    "5909": 'Retorno de bem recebido por conta de contrato de comodato',
    "5911": 'Remessa de amostra grátis',
    "5912": 'Remessa de mercad ou bem p/ demonstração',
    "5913": 'Retorno de mercad ou bem receb p/ demonstração',
    "5914": 'Remessa de mercad ou bem p/ exposição/feira',
    "5917": 'Remessa de mercad em consig mercantil/indust',
    "5918": 'Devolução de mercad recebida em consig mercantil/indust',
    "5919": 'Devolução simbólica de mercad vendida ou utilizada em processo industrial, receb anteriorm em consig mercantil/indust',
    "5920": 'Remessa de vasilhame/sacaria',
    "5921": 'Devolução de vasilhame/sacaria',
    "5922": 'Lanç a título de simples faturamento decorrente de venda p/ entrega futura',
    "5923": 'Remessa de mercad por conta e ordem de terceiros, em venda à ordem',
    "5924": 'Remessa p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do adquirente',
    "5925": 'Retorno de mercad recebida p/indust por conta/ordem do adquirente da mercad, quando aquela sem trânsito pelo estab do...',
    "5926": 'Lanç a título de reclassificação de mercad decorrente de formação de kit ou de sua desagregação',
    "5928": 'Lanç a título de baixa de estoque decorrente do encerramento da atividade da empresa',
    "5929": 'Lanç efetuado por emissão de doc fiscal relativo a operação ou prestação tb registrado em ECF',
    "5931": 'Lanç efetuado em decorrência da responsab retenção imposto por ST, atribuída ao remetente ou alienante da mercad, pel...',
    "5932": 'Prest serv de transporte iniciada em UF diversa daquela onde inscrito o prestador',
    "5933": 'Prest serv tributado pelo ISSQN',
    "6103": "Venda prod do estab, efetuada fora do estab",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "6104": 'Venda de mercad adq/receb terc, efetuada fora do estab',
    "6105": 'Venda de produção do estab sem trânsito pelo estab',
    "6106": 'Venda de mercad adq/receb terc, sem trânsito pelo estab',
    "6107": 'Venda de produção do estab, destinada a não contribuinte',
    "6108": 'Venda de mercad adq/receb terc, destinada a não contribuinte',
    "6109": 'Venda de produção do estab, destinada à ZFM/ALC',
    "6110": 'Venda de mercad adq/receb terc, destinada à ZFM/ALC',
    "6111": 'Venda de produção do estab remet anteriorm em consig indust',
    "6112": 'Venda de mercad adq/receb terc remet anteriorm em consig indust',
    "6113": 'Venda de produção do estab remet anteriorm em consig mercantil',
    "6114": 'Venda de mercad adq/receb terc remet anteriorm em consig mercantil',
    "6115": 'Venda de mercad adq/receb terc, receb anteriorm em consig mercantil',
    "6116": 'Venda de produção do estab originada de encomenda p/ entrega futura',
    "6117": 'Venda de mercad adq/receb terc, originada de encomenda p/ entrega futura',
    "6118": 'Venda de produção do estab entregue ao destinatário por conta/ordem do adquir originário, em venda à ordem',
    "6119": 'Venda de mercad adq/receb terc entregue ao destinatário por conta/ordem do adquir originário, em venda à ordem',
    "6120": 'Venda de mercad adq/receb terc entregue ao destinatário pelo vendedor remetente, em venda à ordem',
    "6122": 'Venda de produção do estab remetida p/indust, por conta/ordem do adquirente, sem transitar pelo estab do adquirente',
    "6123": 'Venda de mercad adq/receb terc remetida p/indust, por conta/ordem do adquirente, sem transitar pelo estab do adquirente',
    "6124": 'Indust efetuada p/ outra empresa',
    "6125": 'Indust efetuada p/ outra empresa quando a mercad receb p/ utilização no processo de indust sem trânsito pelo estab ad...',
    "6151": 'Transferência de produção do estab',
    "6152": 'Transferência de mercad adq/receb terc',
    "6153": 'Transferência de energ elétr',
    "6155": 'Transferência de produção do estab, sem trânsito pelo estab',
    "6156": 'Transferência de mercad adq/receb terc, sem trânsito pelo estab',
    "6201": 'Devolução de compra p/indust ou prod rural',
    "6205": 'Anulação de valor relativo a aquisição de serviço de comunicação',
    "6206": 'Anulação de valor relativo a aquisição de serviço de transporte',
    "6207": 'Anulação de valor relativo à compra de energ elétr',
    "6208": 'Devolução de mercad recebida em transferência p/indust ou prod rural',
    "6209": 'Devolução de mercad recebida em transferência p/comercial',
    "6210": 'Devolução de compra p/ utilização na prest serv',
    "6251": 'Venda de energ elétr p/ distribuição ou comercial',
    "6252": 'Venda de energ elétr p/ estab industrial',
    "6253": 'Venda de energ elétr p/ estab comercial',
    "6254": 'Venda de energ elétr p/ estab prest serv transporte',
    "6255": 'Venda de energ elétr p/ estab prest serv comunicação',
    "6256": 'Venda de energ elétr p/ estab de produtor rural',
    "6257": 'Venda de energ elétr p/ consumo por demanda contratada',
    "6258": 'Venda de energ elétr a não contribuinte',
    "6301": 'Prest serv de comunicação p/ execução de serv mesma natureza',
    "6302": 'Prest serv de comunicação a estab industrial',
    "6303": 'Prest serv de comunicação a estab comercial',
    "6304": 'Prest serv de comunicação a estab de prest serv transporte',
    "6305": 'Prest serv de comunicação a estab de geradora/distrib de energ elétr',
    "6306": 'Prest serv de comunicação a estab de produtor rural',
    "6307": 'Prest serv de comunicação a não contribuinte',
    "6351": 'Prest serv de transporte p/ execução de serv mesma natureza',
    "6352": 'Prest serv de transporte a estab industrial',
    "6353": 'Prest serv de transporte a estab comercial',
    "6354": 'Prest serv de transporte a estab de prest serv comunicação',
    "6355": 'Prest serv de transporte a estab de geradora/distrib de energ elétr',
    "6356": 'Prest serv de transporte a estab de produtor rural',
    "6357": 'Prest serv de transporte a não contribuinte',
    "6359": 'Prest serv de transporte a contribuinte ou a não contribuinte quando a mercad transportada está dispensada de emissão...',
    "6401": 'Venda de produção do estab em operação c/ produto sujeito a ST, na condição de contribuinte substituto',
    "6402": 'Venda de produção do estab de produto sujeito a ST, em operação entre contribuintes substitutos do mesmo produto',
    "6403": 'Venda de mercad adq/receb terc em operação c/ mercad sujeita a ST, na condição de contribuinte substituto',
    "6404": 'Venda de mercad sujeita a ST, cujo imposto já tenha sido retido anteriormente',
    "6408": 'Transferência de produção do estab em operação c/ produto sujeito a ST',
    "6409": 'Transferência de mercad adq/receb terc em operação c/ mercad sujeita a ST',
    "6410": 'Devolução de compra p/indust ou prod rural em operação c/ mercad sujeita a ST',
    "6412": 'Devolução de bem do ativo imob, em operação c/ mercad sujeita a ST',
    "6413": 'Devolução de mercad destinada ao uso/consumo, em operação c/ mercad sujeita a ST',
    "6414": 'Remessa de produção do estab p/venda fora do estab em operação c/ produto sujeito a ST',
    "6415": 'Remessa de mercad adq/receb terc p/venda fora do estab, em operação c/ mercad sujeita a ST',
    "6501": 'Remessa de produção do estab, c/fim espec exportação',
    "6502": 'Remessa de mercad adq/receb terc, c/fim espec exportação',
    "6503": 'Devolução de mercad recebida c/fim espec exportação',
    "6504": 'Remessa de mercads p/ formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estab',
    "6505": 'Remessa de mercads, adq/receb terc, p/ formação de lote de exportação',
    "6552": 'Transferência de bem do ativo imob',
    "6553": 'Devolução de compra de bem p/ o ativo imob',
    "6554": 'Remessa de bem do ativo imob p/ uso fora do estab',
    "6555": 'Devolução de bem do ativo imob de terceiro, receb p/ uso no estab',
    "6557": 'Transferência de material de uso/consumo',
    "6603": 'Ressarcimento de ICMS retido por ST',
    "6651": 'Venda de comb/lubrif de produção do estab destinado à indust subsequente',
    "6652": 'Venda de comb/lubrif de produção do estab destinado à comercial',
    "6653": 'Venda de comb/lubrif de produção do estab destinado a consum/usuár final',
    "6654": 'Venda de comb/lubrif adq/receb terc destinado à indust subsequente',
    "6655": 'Venda de comb/lubrif adq/receb terc destinado à comercial',
    "6656": 'Venda de comb/lubrif adq/receb terc destinado a consum/usuár final',
    "6657": 'Remessa de comb/lubrif adq/receb terc p/venda fora do estab',
    "6658": 'Transferência de comb/lubrif de produção do estab',
    "6659": 'Transferência de comb/lubrif adquirido ou recebido de terceiro',
    "6660": 'Devolução de compra de comb/lubrif adquirido p/indust subsequente',
    "6661": 'Devolução de compra de comb/lubrif adquirido p/comercial',
    "6662": 'Devolução de compra de comb/lubrif adquirido por consum/usuár final',
    "6663": 'Remessa p/ armazenagem de comb/lubrif',
    "6664": 'Retorno de comb/lubrif receb p/ armazenagem',
    "6665": 'Retorno simbólico de comb/lubrif receb p/ armazenagem',
    "6666": 'Remessa por conta e ordem de terceiros de comb/lubrif receb p/ armazenagem',
    "6901": 'Remessa p/indust por encomenda',
    "6902": 'Retorno de mercad utilizada na indust por encomenda',
    "6903": 'Retorno de mercad recebida p/indust e não aplicada no referido processo',
    "6904": 'Remessa p/venda fora do estab',
    "6905": 'Remessa p/ depós fechado/armaz geral',
    "6906": "Ret mercad depositada em dep fechado ou armazém geral",  # CONFIRMADO (MA, Gestão PIS/COFINS)
    "6907": 'Retorno simbólico de mercad depositada em depós fechado/armaz geral',
    "6908": 'Remessa de bem por conta de contrato de comodato',
    "6909": 'Retorno de bem recebido por conta de contrato de comodato',
    "6910": 'Remessa em bonif/doação/brinde',
    "6911": 'Remessa de amostra grátis',
    "6912": 'Remessa de mercad ou bem p/ demonstração',
    "6913": 'Retorno de mercad ou bem receb p/ demonstração',
    "6914": 'Remessa de mercad ou bem p/ exposição/feira',
    "6915": 'Remessa de mercad ou bem p/ conserto/reparo',
    "6916": 'Retorno de mercad ou bem receb p/ conserto/reparo',
    "6917": 'Remessa de mercad em consig mercantil/indust',
    "6918": 'Devolução de mercad recebida em consig mercantil/indust',
    "6919": 'Devolução simbólica de mercad vendida ou utilizada em processo industrial, receb anteriorm em consig mercantil/indust',
    "6920": 'Remessa de vasilhame/sacaria',
    "6921": 'Devolução de vasilhame/sacaria',
    "6922": 'Lanç a título de simples faturamento decorrente de venda p/ entrega futura',
    "6923": 'Remessa de mercad por conta e ordem de terceiros, em venda à ordem',
    "6924": 'Remessa p/indust por conta/ordem do adquirente da mercad, quando esta sem trânsito pelo estab do adquirente',
    "6925": 'Retorno de mercad recebida p/indust por conta/ordem do adquirente da mercad, quando aquela sem trânsito pelo estab do...',
    "6929": 'Lanç efetuado por emissão de doc fiscal relativo a operação ou prestação tb registrado em ECF',
    "6931": 'Lanç efetuado em decorrência da responsab retenção imposto por ST, atribuída ao remetente ou alienante da mercad, pel...',
    "6932": 'Prest serv de transporte iniciada em UF diversa daquela onde inscrito o prestador',
    "6933": 'Prest serv tributado pelo ISSQN',
    "7101": 'Venda de produção do estab',
    "7105": 'Venda de produção do estab, sem trânsito pelo estab',
    "7106": 'Venda de mercad adq/receb terc, sem trânsito pelo estab',
    "7127": 'Venda de produção do estab sob o regime de drawback',
    "7201": 'Devolução de compra p/indust ou prod rural',
    "7202": 'Devolução de compra p/comercial',
    "7205": 'Anulação de valor relativo à aquisição de serviço de comunicação',
    "7206": 'Anulação de valor relativo a aquisição de serviço de transporte',
    "7207": 'Anulação de valor relativo à compra de energ elétr',
    "7210": 'Devolução de compra p/ utilização na prest serv',
    "7211": 'Devolução de compras p/indust sob o regime de drawback',
    "7251": 'Venda de energ elétr p/ o exterior',
    "7301": 'Prest serv de comunicação p/ execução de serv mesma natureza',
    "7358": 'Prest serv de transporte',
    "7501": 'Exportação de mercads recebidas c/fim espec exportação',
    "7551": 'Venda de bem do ativo imob',
    "7553": 'Devolução de compra de bem p/ o ativo imob',
    "7556": 'Devolução de compra de material de uso/consumo',
    "7651": 'Venda de comb/lubrif de produção do estab',
    "7654": 'Venda de comb/lubrif adq/receb terc',
    "7930": 'Lanç a título de devolução de bem cuja entrada tenha ocorrido sob amparo regime especial aduaneiro admissão temp',
}


def descricao(codigo: str) -> str:
    """Retorna a descrição do CFOP, ou string vazia se desconhecido."""
    return TABELA.get((codigo or "").strip(), "")
