"""empresa ampliada, estabelecimento e projeto

Revision ID: 62fe3d195ce5
Revises: 797bb3659b27
Create Date: 2026-09-10 11:16:53.945641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fe3d195ce5'
down_revision: Union[str, Sequence[str], None] = '797bb3659b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('ie', sa.String(length=20), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('e_matriz', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('frente', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('competencia_ini', sa.Date(), nullable=False),
    sa.Column('competencia_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'frente', 'nome')
    )
    op.add_column('empresa', sa.Column('cnpj_matriz', sa.String(length=14), nullable=True))
    op.add_column('empresa', sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
    op.add_column('empresa', sa.Column('pre_cadastro', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('empresa', sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('empresa', sa.Column('criada_por', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empresa', 'usuario', ['criada_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.drop_column('empresa', 'criada_por')
    op.drop_column('empresa', 'criada_em')
    op.drop_column('empresa', 'pre_cadastro')
    op.drop_column('empresa', 'inscricao_estadual')
    op.drop_column('empresa', 'cnpj_matriz')
    op.drop_table('projeto')
    op.drop_table('estabelecimento')
    # ### end Alembic commands ###
