"""estrutura inicial: empresa, usuario e alocacao

Revision ID: 797bb3659b27
Revises: 
Create Date: 2026-09-10 08:22:12.261927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797bb3659b27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_raiz', sa.String(length=8), nullable=False),
    sa.Column('razao_social', sa.Text(), nullable=False),
    sa.Column('grupo_economico', sa.Text(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_raiz')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome_exibicao', sa.Text(), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativas_falhas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('alocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('papel_projeto', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alocado_por', sa.Integer(), nullable=True),
    sa.Column('motivo_saida', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alocado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', 'inicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alocacao')
    op.drop_table('usuario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
