<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cat.Infraestrutura\Cat.Infraestrutura.csproj" />
    <ProjectReference Include="..\Cat.Aplicacao\Cat.Aplicacao.csproj" />
    <ProjectReference Include="..\Cat.Dominio\Cat.Dominio.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
